# Generated by Django 5.1.7 on 2025-07-06 11:06

import django.db.models.deletion
import payments.constants
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("shopping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=100, null=True)),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Success", "Success"),
                            ("Failure", "Failure"),
                            ("Pending", "Pending"),
                            ("Refunded", "Refunded"),
                            ("Cancelled", "Cancelled"),
                            ("Processing", "Processing"),
                            ("Declined", "Declined"),
                        ],
                        default=payments.constants.TransactionStatus["PENDING"],
                        max_length=50,
                    ),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("gateway_response", models.JSONField(blank=True, null=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="shopping.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
