# Generated by Django 5.1.1 on 2024-12-04 09:39

import datetime
import system.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "system_id",
                    models.UUIDField(
                        default=uuid.UUID("90db155d-4453-4631-bde2-03d4bf9a6609"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("system_name", models.CharField(max_length=150)),
                ("smtp_enable", models.BooleanField(default=False)),
                ("smtp_host", models.CharField(max_length=50)),
                ("smtp_username", models.CharField(max_length=100)),
                ("smtp_password", models.CharField(max_length=100)),
                (
                    "created_at",
                    system.utils.DateTimeWithTZField(
                        blank=True,
                        default=datetime.datetime(2024, 12, 4, 9, 39, 26, 148377),
                        null=True,
                    ),
                ),
            ],
        ),
    ]
