# Generated by Django 5.1.1 on 2025-02-04 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "system_id",
                    models.UUIDField(
                        default=uuid.UUID("26dafbbc-b3c0-4143-abfb-cd6a523bbef9"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("system_name", models.CharField(max_length=150)),
                ("smtp_enable", models.BooleanField(default=False)),
                ("smtp_host", models.CharField(max_length=50)),
                ("smtp_username", models.CharField(max_length=100)),
                ("smtp_password", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
