# Generated by Django 4.1.13 on 2024-07-05 14:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='id',
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='system_id',
            field=models.UUIDField(default=uuid.UUID('b11a8a5e-5393-41f0-b73b-136da09bc789'), primary_key=True, serialize=False),
        ),
    ]
