# Generated by Django 4.1.13 on 2024-07-05 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_systemconfig_id_alter_systemconfig_system_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='system_id',
            field=models.UUIDField(default=uuid.UUID('ef00ea96-1a08-4296-8b60-7fb97baf4019'), primary_key=True, serialize=False),
        ),
    ]
