# Generated by Django 4.1.13 on 2024-07-05 14:13

import datetime
from django.db import migrations, models
import system.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_systemconfig_system_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='created_at',
            field=system.utils.DateTimeWithTZField(blank=True, default=datetime.datetime(2024, 7, 5, 14, 13, 17, 942552), null=True),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='system_id',
            field=models.UUIDField(default=uuid.UUID('0f59d40a-53a8-4e00-b04c-8b63a9e04614'), primary_key=True, serialize=False),
        ),
    ]
