# Generated by Django 4.1.13 on 2024-07-05 14:16

import datetime
from django.db import migrations, models
import system.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_systemconfig_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='created_at',
            field=system.utils.DateTimeWithTZField(blank=True, default=datetime.datetime(2024, 7, 5, 14, 16, 1, 534601), null=True),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='system_id',
            field=models.UUIDField(default=uuid.UUID('964ea7a7-9a56-4e36-a457-670be274c50c'), primary_key=True, serialize=False),
        ),
    ]
