# Generated by Django 4.1.13 on 2024-07-05 14:17

import datetime
from django.db import migrations, models
import system.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_systemconfig_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='created_at',
            field=system.utils.DateTimeWithTZField(blank=True, default=datetime.datetime(2024, 7, 5, 14, 17, 17, 578424), null=True),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='system_id',
            field=models.UUIDField(default=uuid.UUID('888d8d63-316c-4fdc-919e-af913aebcfdd'), primary_key=True, serialize=False),
        ),
    ]
