# Generated by Django 4.1.13 on 2024-07-05 14:17

import datetime
from django.db import migrations, models
import system.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_systemconfig_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='created_at',
            field=system.utils.DateTimeWithTZField(blank=True, default=datetime.datetime(2024, 7, 5, 14, 17, 53, 479818), null=True),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='system_id',
            field=models.UUIDField(default=uuid.UUID('c974bb7a-7bf7-4378-a287-27d24ce73eb2'), primary_key=True, serialize=False),
        ),
    ]
