# Generated by Django 4.1.13 on 2024-07-05 14:17

import datetime
from django.db import migrations, models
import system.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_systemconfig_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='created_at',
            field=system.utils.DateTimeWithTZField(blank=True, default=datetime.datetime(2024, 7, 5, 14, 17, 57, 853564), null=True),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='system_id',
            field=models.UUIDField(default=uuid.UUID('02d77d48-e761-45c8-8f22-0cbf472927e7'), primary_key=True, serialize=False),
        ),
    ]
